# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Junkcast!
email: drew@drewlink.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the junkcast™️
baseurl: "/junkcast" # the subpath of your site, e.g. /blog
url: "https://drewstinnett.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: brewerdrewer
github_username: drewstinnett

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
podcast:
  title: JunkCast
  description: Film reviews with Drews friends and family...occasionally other things too
  url: /podcast.xml
  author: Drew Stinnett
  email: drew@drewlink.com
  logo: https://drewstinnett.github.io/junkcast/images/junkcast-logo.jpg
  language: en-US
  category: "TV &amp; Film"
  subcategory: Film Reviews
  type: episodic
  explicit: false
  complete: false
  block: "no"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
